### ISSUE TITLE
Centos7 v3.0.1-rc2 不可逆块和当前块高度差增加

### ISSUE THREAD

**Issue by fufesou** [boscore/bos#116]
昨晚我部署了bos，持续请求接口。一开始记录的get info，高度差是1~2。部署了两个测试环境，每个环境5个BP节点。其他参数没变。

环境1：测试过程中变成了3，早上来变成了7 - 8。
环境2：早上来变成了5 - 6。

并且没有恢复的趋势。不知道怎么恢复，再测试，高度差会不会继续能加。

记录有8小时时区差。
[[昨晚的记录]]
{
  "server_version": "fa2072c3",
  "chain_id": "cf057bbfb72640471fd910bcb67639c22df9f92470936cddc1ade0e2f2e7dc4f",
  "head_block_num": 20514,
  "last_irreversible_block_num": 20511,
  "last_irreversible_block_id": "0000501f9e7657a16dd216a1c649a76f3e0bc70e970b099642de58c452770bca",
  "head_block_id": "000050227d21478a2e3042392965acf85043ff51247422046041beda559c61fe",
  "head_block_time": "2019-07-17T17:44:09.000",
  "head_block_producer": "gabp12",
  "current_view": 0,
  "target_view": 1,
  "last_stable_checkpoint_block_num": 20501,
  "virtual_block_cpu_limit": 200000000,
  "virtual_block_net_limit": 1048576000,
  "block_cpu_limit": 181380,
  "block_net_limit": 1046472,
  "server_version_string": "v3.0.1-rc2-dirty"
}

[[早上的记录]]
{
  "server_version": "fa2072c3",
  "chain_id": "cf057bbfb72640471fd910bcb67639c22df9f92470936cddc1ade0e2f2e7dc4f",
  "head_block_num": 81103,
  "last_irreversible_block_num": 81097,
  "last_irreversible_block_id": "00013cc9574901d347f3be2965a4f34032f66f39df0a0aef22b473c7282bcc06",
  "head_block_id": "00013ccffb5dd60f2de8d0dcf35c87675e404e69123f93a5cfc4e5c56a9d0cd6",
  "head_block_time": "2019-07-18T02:09:03.500",
  "head_block_producer": "gabp11",
  "current_view": 0,
  "target_view": 1,
  "last_stable_checkpoint_block_num": 81001,
  "virtual_block_cpu_limit": 200000000,
  "virtual_block_net_limit": 1048576000,
  "block_cpu_limit": 199900,
  "block_net_limit": 1048576,
  "server_version_string": "v3.0.1-rc2-dirty"
}

**Comment by fufesou** [comment]
我继续跑原来的测试，高度差变成3了

**Comment by fufesou** [comment]
恢复一个块的高度差了。
可以大致讲下吗
是没有交易，高度差就不变，有了交易，高度差会恢复？

**Comment by oldcold** [comment]
> 恢复一个块的高度差了。
> 可以大致讲下吗
> 是没有交易，高度差就不变，有了交易，高度差会恢复？

The difference between `head` and `lib` is likely to be affected by the net traffic and your `nodeos` overload under batch-pbft protocol. Let's say if you are making HTTP requests (e.g. `get_chain_info`) to your bp node at a very high frequency, the overall performance will drop down significantly for sure. 
Moreover, if you could try to carry on your tests on a larger size of bp schedule (e.g. 21, the same with mainnet), the performance should be getting more stable.

**Comment by fufesou** [comment]
> > 恢复一个块的高度差了。
> > 可以大致讲下吗
> > 是没有交易，高度差就不变，有了交易，高度差会恢复？
> 
> The difference between `head` and `lib` is likely to be affected by the net traffic and your `nodeos` overload under batch-pbft protocol. Let's say if you are making HTTP requests (e.g. `get_chain_info`) to your bp node at a very high frequency, the overall performance will drop down significantly for sure.
> Moreover, if you could try to carry on your tests on a larger size of bp schedule (e.g. 21, the same with mainnet), the performance should be getting more stable.

Thank you.
