### ISSUE TITLE
BOSCore v3.0.1-rc2 LIB不走

### ISSUE THREAD

**Issue by fufesou** [boscore/bos#120]
5个BP节点，每个节点出12个块。
出现3次，30秒内lib不走，高度差达到60~76。期间head正常走，节点都在。
然后恢复正常。

![image](https://user-images.githubusercontent.com/13586388/62311801-33a95780-b4bf-11e9-97df-44f08ad814ef.png)

这个是bug吗？如果不是，可以修改哪个配置，减少这种情况呢？

**Comment by oldcold** [comment]
This lib stuck indicated that your chain was under a view change, which is by design. This mechanism is employed to ensure liveness against faulty leaders, temporary network partition, etc. (Please refer to the original pbft algorithm [here](http://pmg.csail.mit.edu/papers/osdi99.pdf))

The view change comes with a timeout (which in the current version is 30 secs), nodes will enter the new view subsequently. To reduce the frequency of view changes,  it is suggested to 1) keep all your nodes connected with each other, 2) adjust the overload of trxns to a level that fits your machine and 3) slightly increase the size of your bp schedule (which is 5 in your case) to avoid any uncertainty.

**Comment by fufesou** [comment]
> This lib stuck indicated that your chain was under a view change, which is by design. This mechanism is employed to ensure liveness against faulty leaders, temporary network partition, etc. (Please refer to the original pbft algorithm [here](http://pmg.csail.mit.edu/papers/osdi99.pdf))
> 
> The view change comes with a timeout (which in the current version is 30 secs), nodes will enter the new view subsequently. To reduce the frequency of view changes, it is suggested to 1) keep all your nodes connected with each other, 2) adjust the overload of trxns to a level that fits your machine and 3) slightly increase the size of your bp schedule (which is 5 in your case) to avoid any uncertainty.

Thank you.  As you say, lib stuck wont be longer than 30 secs in my version?
1)  I have made all nodes connected to each other before.
2) The overload is not in high level in a time.
3) emm, hard^_^.

What if i decrease blocks that a node produce continuously。12 to 3? Will the view change timeout be shorten to 8 secs?

**Comment by fufesou** [comment]
> This lib stuck indicated that your chain was under a view change, which is by design. This mechanism is employed to ensure liveness against faulty leaders, temporary network partition, etc. (Please refer to the original pbft algorithm [here](http://pmg.csail.mit.edu/papers/osdi99.pdf))
> 
> The view change comes with a timeout (which in the current version is 30 secs), nodes will enter the new view subsequently. To reduce the frequency of view changes, it is suggested to 1) keep all your nodes connected with each other, 2) adjust the overload of trxns to a level that fits your machine and 3) slightly increase the size of your bp schedule (which is 5 in your case) to avoid any uncertainty.

I've read the white paper. 
    "After the introduction of PBFT, in order to avoid the fork which may cause the consensus to become unable to advance, the view change mechanism is introduced. All unconsented information is discarded and consensus procedures are continually attempted until the consensus is made." 

View change works until the consensus is made. You said "The view change comes with a timeout ".  What if the consensus is not made after 30 secs? Is it work as the following shows?
 
view change --> consensus is made----(30 secs)----> view change end, lib move

Thank you

**Comment by oldcold** [comment]
>> 
> View change works until the consensus is made. You said "The view change comes with a timeout ". What if the consensus is not made after 30 secs? Is it work as the following shows?
> 
>>
The view change will happen only if the LIB is not advancing after a period of time (say 30 secs here), and this is used to get the chain back to work.

**Comment by oldcold** [comment]
> >  
> What if i decrease blocks that a node produce continuously。12 to 3? Will the view change timeout be shorten to 8 secs?
>>
How do you achieve this? By modifying the source code?

**Comment by fufesou** [comment]
> > > 
> > 
> > 
> > What if i decrease blocks that a node produce continuously。12 to 3? Will the view change timeout be shorten to 8 secs?
> > >
> 
> How do you achieve this? By modifying the source code?

Yes

**Comment by fufesou** [comment]
> > > 
> > 
> > 
> > View change works until the consensus is made. You said "The view change comes with a timeout ". What if the consensus is not made after 30 secs? Is it work as the following shows?
> > >
> 
> The view change will happen only if the LIB is not advancing after a period of time (say 30 secs here), and this is used to get the chain back to work.

View change happens after lib stops advancing after (30 secs)? Isn't it the reason why lib is on stuck? I'm confused ~_~

**Comment by oldcold** [comment]
> >
> View change happens after lib stops advancing after (30 secs)? Isn't it the reason why lib is on stuck? I'm confused ~_~
>>
LIB is likely to be frozen due to various reasons in the wild, as I have mentioned in the very first reply, and that's why the view change mechanism is needed. 

In short, if LIB stop for some time, a view change action will be triggered, during the view change state, nodes will attempt to sync all pbft related information (within a reasonable range) one more time to resume the consensus.

**Comment by fufesou** [comment]
> > > 
> > 
> > 
> > View change happens after lib stops advancing after (30 secs)? Isn't it the reason why lib is on stuck? I'm confused ~_~
> > >
> 
> LIB is likely to be frozen due to various reasons in the wild, as I have mentioned in the very first reply, and that's why the view change mechanism is needed.
> 
> In short, if LIB stop for some time, a view change action will be triggered, during the view change state, nodes will attempt to sync all pbft related information (within a reasonable range) one more time to resume the consensus.

I understand, maybe. Some statement triggers view change. View change take at least 30 secs in my version? 
I'll learn pbft in a time later. Thank you for your help.
