### ISSUE TITLE
Do you plan to merge the v1.8.x branch code?

### ISSUE THREAD

**Issue by cppfuns** [boscore/bos#132]
RT

**Comment by Thaipanda** [comment]
not all v1.8.x code, what is the most important is EOSVM, which is under merging

**Comment by cppfuns** [comment]
Why not upgrade to 1.8.x overall? And after the 2.x branch, there should be a lot of new features and stability advantages

**Comment by Thaipanda** [comment]
BOSCore has its own roadmap and plan, some features will pick from EOSIO, for example VM 2.0, Web Authn etc.

can you give some suggestion, which feature you want to have and why？

**Comment by matthewdarwin** [comment]
I would like `database-map-mode = locked` so I can run the entire blockchain in RAM and I don't need fast disks.

**Comment by cppfuns** [comment]
Recently, I tried to move the function of the original 1.6.3 version to 2.0, and found that many data structures have changed, and I couldn't find a corresponding method. It is indeed difficult to upgrade.
