### ISSUE TITLE
How to promote TPS

### ISSUE THREAD

**Issue by zhopen** [boscore/bos#145]
I did press test.  when TPS is only 360, Transaction can be executed and confrimed smoothly  within 3 sconds, if  TPS is too big ,  a lot of transactions can't be executed and confirmed timely . These transactions are buffered and will be executed until stop requesting transactions.    

Anyone could tell me how to promote TPS , 360 is too low.

**Comment by zhopen** [comment]
I optimized for block chain,TPS go up to 600.
how much is max TPS of BOS MAINNET

**Comment by matthewdarwin** [comment]
According to https://bos.bloks.io/, max TPS is 3898

**Comment by Thaipanda** [comment]
the TPS rely on multi-factors. for example, please check your machine CPU/NET situation; and try to find a better style to write smart contracts. there are lots of article to refer.
