### ISSUE TITLE
Support 1.8/2.0 SHIP stream format

### ISSUE THREAD

**Issue by matthewdarwin** [boscore/bos#152]
We want to upgrade to latest version of Hyperion soon.  The new hyperion does not support the old SHIP (state history plugin) compressed stream as that is quite old.  BOS still uses this.

Can BOS please update to the new state history format used in nodeos 1.8 and 2.0 so it can be compatible to the many open source tools out there that use SHIP.

Without this, we will be forced to drop Hyperion support for BOS.

**Comment by matthewdarwin** [comment]
To be clear, this is about removing compression from the SHIP output.

**Comment by Thaipanda** [comment]
nice suggestion. I think we can do this after the VM 2.0 version upgrade, it might need about one month time.
