### ISSUE TITLE
能否提供表row_count的API?

### ISSUE THREAD

**Issue by xiangxn** [boscore/bos#17]
能否提供表row_count的API?
目前只能自己从begin()++到end()，这是唯一方法吗？
如果能提供查到记录数，对有的业务需求是相当友好的，一个是rpcapi,一个是合约内。

> 另外，如果可以加入http模块就好了，我的合约需要异步向中心服务器post数据。

**Comment by Thaipanda** [comment]
can you give more detail description about the demand? why not you add an increase clomun to get this?

**Comment by xiangxn** [comment]
column？
一个最精典的业务要求是，当数据量达到N条时，我将触发一个逻辑。
但目前，我只能加一个字段来计数:)

**Comment by vlbos** [comment]
我们在考虑增加类似参考实现方案https://bihu.com/article/1256560

**Comment by Thaipanda** [comment]
will make a whole plan to improve the multi-index in the future
