### ISSUE TITLE
After executing linkauth，How to query which action is linked to the permission 

### ISSUE THREAD

**Issue by zhopen** [boscore/bos#172]
I create new permission "alice@default" under "alice@active" ， and linkauth hello::hi action to "default@alice" permission.
After doing that, How to query what auth is linked in permission alice@default.

**Comment by Frank-AFN** [comment]
option1: you could try hyperion state_history_plugin api. https://wax.eosrio.io/v2/docs/index.html#/accounts/get_v2_state_get_links

option2: check from bloks.io explorer in the `keys` tab. It will show all information of your account.
