### ISSUE TITLE
Unable to make install librdkafka

### ISSUE THREAD

**Issue by lvgang214** [boscore/bos#35]
执行eosio_build.sh  ，安装librdkafka时提示失败
TopicImpl.cpp:(.text+0x1c8)：对‘__dynamic_cast’未定义的引用
TopicImpl.cpp:(.text+0x1da)：对‘operator new(unsigned long)’未定义的引用
TopicImpl.cpp:(.text+0x2bd)：对‘std::string::c_str() const’未定义的引用
TopicImpl.cpp:(.text+0x301)：对‘std::string::operator=(char const*)’未定义的引用
../src-cpp/librdkafka++.a(TopicImpl.cpp.o)：在函数‘__static_initialization_and_destruction_0(int, int)’中：
TopicImpl.cpp:(.text+0x372)：对‘std::ios_base::Init::Init()’未定义的引用
TopicImpl.cpp:(.text+0x387)：对‘std::ios_base::Init::~Init()’未定义的引用
../src-cpp/librdkafka++.a(TopicImpl.cpp.o)：在函数‘RdKafka::TopicImpl::~TopicImpl()’中：
TopicImpl.cpp:(.text._ZN7RdKafka9TopicImplD2Ev[_ZN7RdKafka9TopicImplD5Ev]+0x4c)：对‘operator delete(void*)’未定义的引用
../src-cpp/librdkafka++.a(TopicImpl.cpp.o)：在函数‘RdKafka::TopicImpl::~TopicImpl()’中：
TopicImpl.cpp:(.text._ZN7RdKafka9TopicImplD0Ev[_ZN7RdKafka9TopicImplD0Ev]+0x20)：对‘operator delete(void*)’未定义的引用
../src-cpp/librdkafka++.a(TopicImpl.cpp.o)：在函数‘RdKafka::TopicImpl::name() const’中：
TopicImpl.cpp:(.text._ZNK7RdKafka9TopicImpl4nameEv[_ZNK7RdKafka9TopicImpl4nameEv]+0x19)：对‘std::allocator<char>::allocator()’未定义的引用
TopicImpl.cpp:(.text._ZNK7RdKafka9TopicImpl4nameEv[_ZNK7RdKafka9TopicImpl4nameEv]+0x3f)：对‘std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&)’未定义的引用
TopicImpl.cpp:(.text._ZNK7RdKafka9TopicImpl4nameEv[_ZNK7RdKafka9TopicImpl4nameEv]+0x4b)：对‘std::allocator<char>::~allocator()’未定义的引用
TopicImpl.cpp:(.text._ZNK7RdKafka9TopicImpl4nameEv[_ZNK7RdKafka9TopicImpl4nameEv]+0x5c)：对‘std::allocator<char>::~allocator()’未定义的引用
../src-cpp/librdkafka++.a(TopicImpl.cpp.o):(.data.rel.ro._ZTVN7RdKafka5TopicE[_ZTVN7RdKafka5TopicE]+0x10)：对‘__cxa_pure_virtual’未定义的引用
../src-cpp/librdkafka++.a(TopicImpl.cpp.o):(.data.rel.ro._ZTVN7RdKafka5TopicE[_ZTVN7RdKafka5TopicE]+0x18)：对‘__cxa_pure_virtual’未定义的引用
../src-cpp/librdkafka++.a(TopicImpl.cpp.o):(.data.rel.ro._ZTVN7RdKafka5TopicE[_ZTVN7RdKafka5TopicE]+0x20)：对‘__cxa_pure_virtual’未定义的引用
../src-cpp/librdkafka++.a(TopicImpl.cpp.o):(.data.rel.ro._ZTVN7RdKafka5TopicE[_ZTVN7RdKafka5TopicE]+0x28)：对‘__cxa_pure_virtual’未定义的引用
../src-cpp/librdkafka++.a(TopicImpl.cpp.o):(.data.rel.ro._ZTVN7RdKafka5TopicE[_ZTVN7RdKafka5TopicE]+0x30)：对‘__cxa_pure_virtual’未定义的引用
../src-cpp/librdkafka++.a(TopicImpl.cpp.o):(.data.rel.ro._ZTVN7RdKafka5TopicE[_ZTVN7RdKafka5TopicE]+0x38): 跟着更多未定义的参考到 __cxa_pure_virtual
../src-cpp/librdkafka++.a(TopicImpl.cpp.o):(.data.rel.ro._ZTIN7RdKafka9TopicImplE[_ZTIN7RdKafka9TopicImplE]+0x0)：对‘vtable for __cxxabiv1::__si_class_type_info’未定义的引用
../src-cpp/librdkafka++.a(TopicImpl.cpp.o):(.data.rel.ro._ZTIN7RdKafka5TopicE[_ZTIN7RdKafka5TopicE]+0x0)：对‘vtable for __cxxabiv1::__class_type_info’未定义的引用
collect2: 错误：ld 返回 1
make[2]: *** [examples/CMakeFiles/rdkafka_consumer_example_cpp.dir/build.make:100：examples/rdkafka_consumer_example_cpp] 错误 1
make[1]: *** [CMakeFiles/Makefile2:283：examples/CMakeFiles/rdkafka_consumer_example_cpp.dir/all] 错误 2
make: *** [Makefile:139：all] 错误 2

具体是什么原因？是安装对cmake 和C++ 的版本有要求么 ？

**Comment by GXKe** [comment]
很可能是版本不匹配原因，试试删除旧版
[kafka doc](https://github.com/boscore/bos/tree/master/plugins/kafka_plugin)

**Comment by lvgang214** [comment]
> 
> 
> 很可能是版本不匹配原因，试试删除旧版
> [kafka doc](https://github.com/boscore/bos/tree/master/plugins/kafka_plugin)

都没有找到cppkafaka 和 librdkafka  librdkafka编译失败了
