### ISSUE TITLE
能否增加删除表或者清空表的功能？

### ISSUE THREAD

**Issue by addincaoy** [boscore/bos#38]
现在EOS清空表，只能一条条数据删除，效率不够快。希望能增加一个方法，直接删除表，或者清空表。

**Comment by vlbos** [comment]
> 现在EOS清空表，只能一条条数据删除，效率不够快。希望能增加一个方法，直接删除表，或者清空表。

感谢你的建议。正在确定合适的方案实现

**Comment by Thaipanda** [comment]
if we want to operate the multi-index real like a DB, we need make a whole design
