### ISSUE TITLE
在centos7的环境下，eosio_builder.sh 建议增加对cmake的检测。

### ISSUE THREAD

**Issue by lokyliu** [boscore/bos#39]
cmake3.5.x编译代码时，多次提示不成功，最后重启服务器后，对脚本增加cmake的检测安装后，成功运行，建议添加

**Comment by lvgang214** [comment]
你编译代码 是哪里提示不成功 ？librdkafka？还是cppkafka ？还是在之前，我手动去build 这两个成功了 ，但是build bos  还是失败

**Comment by lokyliu** [comment]
cppkafka,这个时候需要安装cmake3.5.x及以上版本，会提示和链的不兼容，无视重启主机后，即可成功

**Comment by vlbos** [comment]
> cmake3.5.x编译代码时，多次提示不成功，最后重启服务器后，对脚本增加cmake的检测安装后，成功运行，建议添加

非常感谢您的建议，后续增加并加强 centos测试
