### ISSUE TITLE
限制抵押操作中只有 transfer 为 false 的才能走 unstaking fund

### ISSUE THREAD

**Issue by snowlybetter** [boscore/bos#4]
限制抵押操作中只有 transfer 为 false 的才能走 unstaking fund；transfer 走 balance，非 transfer 优先走 unstaking；修改代码位置连接：https://github.com/EOSIO/eosio.contracts/blob/v1.2.1/eosio.system/src/delegate_bandwidth.cpp#L299

**Comment by vlbos** [comment]
实现逻辑   bool is_delegating_to_self = (!transfer && from == receiver);修改为   bool is_delegating_to_self = (!transfer );
