### ISSUE TITLE
BOS主网的区块同步地址在哪可以获取?

### ISSUE THREAD

**Issue by wangyilin1987** [boscore/bos#40]
你好，我没有找到BOS主网的区块同步地址，各BP节点也没公布，请问是暂时只向BP节点开放节点吗？

**Comment by snowlybetter** [comment]
https://github.com/boscore/bosres/pull/1/files#diff-740f4cbd7185e91adfe744ffe265742d这里已经提交了一个关于主网peer-address 的pr，你可以使用这个，另外，可以加入bos的电报群https://t.me/boscorecommunity
