### ISSUE TITLE
BOS编译遇到问题

### ISSUE THREAD

**Issue by destiny008** [boscore/bos#41]
[ 71%] Built target Emscripten
CMakeFiles/chainbase_test.dir/test.cpp.o: In function `open_and_create::test_method()':
/data04/bos/bos/libraries/chainbase/test/test.cpp:(.text+0xb08): undefined reference to `boost::test_tools::tt_detail::report_assertion(boost::test_tools::assertion_result const&, boost::unit_test::lazy_ostream const&, boost::unit_test::basic_cstring<char const>, unsigned long, boost::test_tools::tt_detail::tool_level, boost::test_tools::tt_detail::check_type, unsigned long, ...)'
/data04/bos/bos/libraries/chainbase/test/test.cpp:(.text+0xcc8): undefined reference to `boost::test_tools::tt_detail::report_assertion(boost::test_tools::assertion_result const&, boost::unit_test::lazy_ostream const&, boost::unit_test::basic_cstring<char const>, unsigned long, boost::test_tools::tt_detail::tool_level, boost::test_tools::tt_detail::check_type, unsigned long, ...)'
/data04/bos/bos/libraries/chainbase/test/test.cpp:(.text+0xfdd): undefined reference to `boost::test_tools::tt_detail::report_assertion(boost::test_tools::assertion_result const&, boost::unit_test::lazy_ostream const&, boost::unit_test::basic_cstring<char const>, unsigned long, boost::test_tools::tt_detail::tool_level, boost::test_tools::tt_detail::check_type, unsigned long, ...)'
/data04/bos/bos/libraries/chainbase/test/test.cpp:(.text+0x2238): undefined reference to `boost::test_tools::tt_detail::report_assertion(boost::test_tools::assertion_result const&, boost::unit_test::lazy_ostream const&, boost::unit_test::basic_cstring<char const>, unsigned long, boost::test_tools::tt_detail::tool_level, boost::test_tools::tt_detail::check_type, unsigned long, ...)'
/data04/bos/bos/libraries/chainbase/test/test.cpp:(.text+0x36e4): undefined reference to `boost::test_tools::tt_detail::report_assertion(boost::test_tools::assertion_result const&, boost::unit_test::lazy_ostream const&, boost::unit_test::basic_cstring<char const>, unsigned long, boost::test_tools::tt_detail::tool_level, boost::test_tools::tt_detail::check_type, unsigned long, ...)'
CMakeFiles/chainbase_test.dir/test.cpp.o:/data04/bos/bos/libraries/chainbase/test/test.cpp:(.text+0x38d6): more undefined references to `boost::test_tools::tt_detail::report_assertion(boost::test_tools::assertion_result const&, boost::unit_test::lazy_ostream const&, boost::unit_test::basic_cstring<char const>, unsigned long, boost::test_tools::tt_detail::tool_level, boost::test_tools::tt_detail::check_type, unsigned long, ...)' follow
CMakeFiles/chainbase_test.dir/test.cpp.o: In function `boost::unit_test::make_test_case(boost::function<void ()> const&, boost::unit_test::basic_cstring<char const>, boost::unit_test::basic_cstring<char const>, unsigned long)':
/data04/bos/bos/libraries/chainbase/test/test.cpp:(.text._ZN5boost9unit_test14make_test_caseERKNS_8functionIFvvEEENS0_13basic_cstringIKcEES8_m[_ZN5boost9unit_test14make_test_caseERKNS_8functionIFvvEEENS0_13basic_cstringIKcEES8_m]+0x6c): undefined reference to `boost::unit_test::test_case::test_case(boost::unit_test::basic_cstring<char const>, boost::unit_test::basic_cstring<char const>, unsigned long, boost::function<void ()> const&)'
CMakeFiles/chainbase_test.dir/test.cpp.o: In function `bool boost::test_tools::tt_detail::check_frwd<boost::test_tools::tt_detail::equal_impl_frwd, int, int>(boost::test_tools::tt_detail::equal_impl_frwd, boost::unit_test::lazy_ostream const&, boost::unit_test::basic_cstring<char const>, unsigned long, boost::test_tools::tt_detail::tool_level, boost::test_tools::tt_detail::check_type, int const&, char const*, int const&, char const*)':
/data04/bos/bos/libraries/chainbase/test/test.cpp:(.text._ZN5boost10test_tools9tt_detail10check_frwdINS1_15equal_impl_frwdEiiEEbT_RKNS_9unit_test12lazy_ostreamENS5_13basic_cstringIKcEEmNS1_10tool_levelENS1_10check_typeERKT0_PSA_RKT1_SH_[_ZN5boost10test_tools9tt_detail10check_frwdINS1_15equal_impl_frwdEiiEEbT_RKNS_9unit_test12lazy_ostreamENS5_13basic_cstringIKcEEmNS1_10tool_levelENS1_10check_typeERKT0_PSA_RKT1_SH_]+0x155): undefined reference to `boost::test_tools::tt_detail::report_assertion(boost::test_tools::assertion_result const&, boost::unit_test::lazy_ostream const&, boost::unit_test::basic_cstring<char const>, unsigned long, boost::test_tools::tt_detail::tool_level, boost::test_tools::tt_detail::check_type, unsigned long, ...)'
CMakeFiles/chainbase_test.dir/test.cpp.o: In function `_GLOBAL__sub_I_test.cpp':
/data04/bos/bos/libraries/chainbase/test/test.cpp:(.text.startup+0x12b): undefined reference to `boost::unit_test::ut_detail::auto_test_unit_registrar::auto_test_unit_registrar(boost::unit_test::test_case*, boost::unit_test::decorator::collector&, unsigned long)'
[ 72%] Built target appbase_example
clang: error: linker command failed with exit code 1 (use -v to see invocation)
libraries/chainbase/test/CMakeFiles/chainbase_test.dir/build.make:103: recipe for target 'libraries/chainbase/test/chainbase_test' failed
make[2]: *** [libraries/chainbase/test/chainbase_test] Error 1
CMakeFiles/Makefile2:1005: recipe for target 'libraries/chainbase/test/CMakeFiles/chainbase_test.dir/all' failed
make[1]: *** [libraries/chainbase/test/CMakeFiles/chainbase_test.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 72%] Built target WAST
[ 77%] Built target fc
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

	>>>>>>>>>>>>>>>>>>>> MAKE building BOSCore has exited with the above error.

**Comment by destiny008** [comment]
编译了好几遍了 都是这个问题，build文件夹删除以后还是报这个错误，请帮忙分析一下

**Comment by blockchainguard** [comment]
完全是复制eos的代码啊，我劝你善良！

**Comment by vlbos** [comment]
> 编译了好几遍了 都是这个问题，build文件夹删除以后还是报这个错误，请帮忙分析一下

什么操作系统？

**Comment by snowlybetter** [comment]
是用的tag版本么，请用tag版本进行编译

**Comment by vlbos** [comment]
> [ 71%] Built target Emscripten
> CMakeFiles/chainbase_test.dir/test.cpp.o: In function `open_and_create::test_method()': /data04/bos/bos/libraries/chainbase/test/test.cpp:(.text+0xb08): undefined reference to `boost::test_tools::tt_detail::report_assertion(boost::test_tools::assertion_result const&, boost::unit_test::lazy_ostream const&, boost::unit_test::basic_cstring, unsigned long, boost::test_tools::tt_detail::tool_level, boost::test_tools::tt_detail::check_type, unsigned long, ...)'
> /data04/bos/bos/libraries/chainbase/test/test.cpp:(.text+0xcc8): undefined reference to `boost::test_tools::tt_detail::report_assertion(boost::test_tools::assertion_result const&, boost::unit_test::lazy_ostream const&, boost::unit_test::basic_cstring<char const>, unsigned long, boost::test_tools::tt_detail::tool_level, boost::test_tools::tt_detail::check_type, unsigned long, ...)' /data04/bos/bos/libraries/chainbase/test/test.cpp:(.text+0xfdd): undefined reference to `boost::test_tools::tt_detail::report_assertion(boost::test_tools::assertion_result const&, boost::unit_test::lazy_ostream const&, boost::unit_test::basic_cstring, unsigned long, boost::test_tools::tt_detail::tool_level, boost::test_tools::tt_detail::check_type, unsigned long, ...)'
> /data04/bos/bos/libraries/chainbase/test/test.cpp:(.text+0x2238): undefined reference to `boost::test_tools::tt_detail::report_assertion(boost::test_tools::assertion_result const&, boost::unit_test::lazy_ostream const&, boost::unit_test::basic_cstring<char const>, unsigned long, boost::test_tools::tt_detail::tool_level, boost::test_tools::tt_detail::check_type, unsigned long, ...)' /data04/bos/bos/libraries/chainbase/test/test.cpp:(.text+0x36e4): undefined reference to `boost::test_tools::tt_detail::report_assertion(boost::test_tools::assertion_result const&, boost::unit_test::lazy_ostream const&, boost::unit_test::basic_cstring, unsigned long, boost::test_tools::tt_detail::tool_level, boost::test_tools::tt_detail::check_type, unsigned long, ...)'
> CMakeFiles/chainbase_test.dir/test.cpp.o:/data04/bos/bos/libraries/chainbase/test/test.cpp:(.text+0x38d6): more undefined references to `boost::test_tools::tt_detail::report_assertion(boost::test_tools::assertion_result const&, boost::unit_test::lazy_ostream const&, boost::unit_test::basic_cstring<char const>, unsigned long, boost::test_tools::tt_detail::tool_level, boost::test_tools::tt_detail::check_type, unsigned long, ...)' follow CMakeFiles/chainbase_test.dir/test.cpp.o: In function `boost::unit_test::make_test_case(boost::function<void ()> const&, boost::unit_test::basic_cstring, boost::unit_test::basic_cstring, unsigned long)':
> /data04/bos/bos/libraries/chainbase/test/test.cpp:(.text._ZN5boost9unit_test14make_test_caseERKNS_8functionIFvvEEENS0_13basic_cstringIKcEES8_m[_ZN5boost9unit_test14make_test_caseERKNS_8functionIFvvEEENS0_13basic_cstringIKcEES8_m]+0x6c): undefined reference to `boost::unit_test::test_case::test_case(boost::unit_test::basic_cstring<char const>, boost::unit_test::basic_cstring<char const>, unsigned long, boost::function<void ()> const&)' CMakeFiles/chainbase_test.dir/test.cpp.o: In function `bool boost::test_tools::tt_detail::check_frwd<boost::test_tools::tt_detail::equal_impl_frwd, int, int>(boost::test_tools::tt_detail::equal_impl_frwd, boost::unit_test::lazy_ostream const&, boost::unit_test::basic_cstring, unsigned long, boost::test_tools::tt_detail::tool_level, boost::test_tools::tt_detail::check_type, int const&, char const*, int const&, char const*)':
> /data04/bos/bos/libraries/chainbase/test/test.cpp:(.text._ZN5boost10test_tools9tt_detail10check_frwdINS1_15equal_impl_frwdEiiEEbT_RKNS_9unit_test12lazy_ostreamENS5_13basic_cstringIKcEEmNS1_10tool_levelENS1_10check_typeERKT0_PSA_RKT1_SH_[_ZN5boost10test_tools9tt_detail10check_frwdINS1_15equal_impl_frwdEiiEEbT_RKNS_9unit_test12lazy_ostreamENS5_13basic_cstringIKcEEmNS1_10tool_levelENS1_10check_typeERKT0_PSA_RKT1_SH_]+0x155): undefined reference to `boost::test_tools::tt_detail::report_assertion(boost::test_tools::assertion_result const&, boost::unit_test::lazy_ostream const&, boost::unit_test::basic_cstring<char const>, unsigned long, boost::test_tools::tt_detail::tool_level, boost::test_tools::tt_detail::check_type, unsigned long, ...)' CMakeFiles/chainbase_test.dir/test.cpp.o: In function `_GLOBAL__sub_I_test.cpp':
> /data04/bos/bos/libraries/chainbase/test/test.cpp:(.text.startup+0x12b): undefined reference to `boost::unit_test::ut_detail::auto_test_unit_registrar::auto_test_unit_registrar(boost::unit_test::test_case*, boost::unit_test::decorator::collector&, unsigned long)'
> [ 72%] Built target appbase_example
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> libraries/chainbase/test/CMakeFiles/chainbase_test.dir/build.make:103: recipe for target 'libraries/chainbase/test/chainbase_test' failed
> make[2]: *** [libraries/chainbase/test/chainbase_test] Error 1
> CMakeFiles/Makefile2:1005: recipe for target 'libraries/chainbase/test/CMakeFiles/chainbase_test.dir/all' failed
> make[1]: *** [libraries/chainbase/test/CMakeFiles/chainbase_test.dir/all] Error 2
> make[1]: *** Waiting for unfinished jobs....
> [ 72%] Built target WAST
> [ 77%] Built target fc
> Makefile:138: recipe for target 'all' failed
> make: *** [all] Error 2
> 
> ```
> >>>>>>>>>>>>>>>>>>>> MAKE building BOSCore has exited with the above error.
> ```

查看eosio_build.sh  BOOST_ROOT 所指文件夹是否能找到要求boost版本，不能找或版本与要求不一致。
