### ISSUE TITLE
How about header for http packet in notify_plugin

### ISSUE THREAD

**Issue by Onotoko** [boscore/bos#50]
When I create a express server to receive http packet from notify_plugin, and I got undefined result

**Comment by snowlybetter** [comment]
Would you mind explainning it more clearly?

**Comment by Onotoko** [comment]
Hi, thank you for support. 
I have an error when using notify_plugin, on my server, I cannot receive any information of block, it only prints **_undefine._** Here is detail 
**On my nodeos:**

> warn  2019-03-06T04:25:03.008 thread-1  http_async_client.hpp:94      post_sync            ] 4 parse_error_exception: Parse Error
> Unexpected char ‘79’ in “OK”
>    {“c”:79,“s”:“OK”}
>    thread-1  json.cpp:437 variant_from_stream
> 
>    {“str”:“OK”}
>    thread-1  json.cpp:460 from_string
> warn  2019-03-06T04:25:03.008 thread-1  http_async_client.hpp:94      post_sync            ] dest: http://127.0.0.1:8082/notify payload: {“irreversible”:true,“actions”:[{“tx_id”:“a77e5c7c28dd10d11d0cc7e5e6f50bfe211b60a14d9efebe1f8099ee3a694972",“account”:“lala”,“name”:“creatuser”,“seq_num”:0,“receiver”:“lala”,“block_time”:“2019-03-06T04:25:02.000”,“block_num”:96343,“authorization”:[{“actor”:“lalala”,“permission”:“active”}],“action_data”:{“username”:“lalala”,“user_id”:22,“user_name”:“frist”}}]} deadline: 2019-03-06T04:25:13.004


**On my server: (I show code)**

> const express = require(‘express’);
> const app = express()
> 
> const port = 8082
> 
> app.post(‘/notify’, function (req, res) {
>  console.log(req.body)
>  console.log(req) **//It will be log :'undefine'**
> 
>  res.sendStatus(200)
> });
> app.listen(port, () => console.log(`Example app listening on port ${port}!`))

**Comment by snowlybetter** [comment]
```
## Notify Plugin
plugin = eosio::notify_plugin
# notify-filter-on = account:action
notify-filter-on = b1:
notify-filter-on = b1:transfer
notify-filter-on = eosio:delegatebw
# http endpoint for each action seen on the chain.
notify-receive-url = http://127.0.0.1:8080/notify
# Age limit in seconds for blocks to send notifications. No age limit if set to negative.
# Used to prevent old actions from trigger HTTP request while on replay (seconds)
notify-age-limit = -1
# Retry times of sending http notification if failed.
notify-retry-times = 3
```
do you add above parameter to your config.ini?

**Comment by Onotoko** [comment]
Yes, here is my config.ini:

```
# Plugin(s) to enable, may be specified multiple times
# plugin =
plugin = eosio::chain_api_plugin
plugin = eosio::history_api_plugin
plugin = eosio::producer_plugin
## Notify Plugin
plugin = eosio::notify_plugin
notify-filter-on = lala:creatuser
# http endpoint for each action seen on the chain.
notify-receive-url = http://127.0.0.1:8082/notify
# Age limit in seconds for blocks to send notifications. No age limit if set to negative.
# Used to prevent old actions from trigger HTTP request while on replay (seconds)
notify-age-limit = -1
# Retry times of sending http notification if failed.
notify-retry-times = 3
```

**Comment by snowlybetter** [comment]
i see the information,
```
thread-1 json.cpp:460 from_string
warn 2019-03-06T04:25:03.008 thread-1 http_async_client.hpp:94 post_sync ] dest: http://127.0.0.1:8082/notify payload: {“irreversible”:true,“actions”:[{“tx_id”:“a77e5c7c28dd10d11d0cc7e5e6f50bfe211b60a14d9efebe1f8099ee3a694972",“account”:“lala”,“name”:“creatuser”,“seq_num”:0,“receiver”:“lala”,“block_time”:“2019-03-06T04:25:02.000”,“block_num”:96343,“authorization”:[{“actor”:“lalala”,“permission”:“active”}],“action_data”:{“username”:“lalala”,“user_id”:22,“user_name”:“frist”}}]} 
```
there will be  samiler message send for you service.
`On my server: (I show code)

const express = require(‘express’);
const app = express()

const port = 8082

app.post(‘/notify’, function (req, res) {
console.log(req.body)
console.log(req) //It will be log :'undefine'

res.sendStatus(200)
});
app.listen(port, () => console.log(Example app listening on port ${port}!))`
maybe the problem is your server.

**Comment by Onotoko** [comment]
Thank you very much, I found a mistake.
