### ISSUE TITLE
RequiredError: location in Docker Enviroment when use regproducer and set location

### ISSUE THREAD

**Issue by Gshelterm** [boscore/bos#71]
In docker enviroment use boscore/bos:latest image.
I have aleady  set contracts and use use ```system newaccount``` create account
```
sudo docker exec nodeosd cleos system newaccount eosio bp1 EOS7japcYUEQprwmt4W3RLSq1Fp6PueSwMQFt8FFHuDpDouZgSeZ9 EOS7japcYUEQprwmt4W3RLSq1Fp6PueSwMQFt8FFHuDpDouZgSeZ9 --stake-net "1000000.0000 BOS" --    stake-cpu "1000000.0000 BOS" --buy-ram-kbytes "128000 KiB"
```
but when I registered the new account as a producer，encountered a problem that command need a location, then I set location:
```
sudo docker exec nodeosd cleos system regproducer bp1 EOS7japcYUEQprwmt4W3RLSq1Fp6PueSwMQFt8FFHuDpDouZgSeZ9 2
```
stilling get the error,  have tried 0 / 1 / '0' in posiiton of location in command:
```
ERROR: RequiredError: location
Register a new producer
Usage: cleos system regproducer [OPTIONS] account producer_key [url] location

Positionals:
  account TEXT                The account to register as a producer (required)
  producer_key TEXT           The producer's public key (required)
  url TEXT                    url where info about producer can be found
  location INT=0              time zone from -11 to 12 (required)
```
Anyone knows how to solve this, please tell me.

**Comment by snowlybetter** [comment]
```
 cleos system regproducer 
ERROR: RequiredError: account
Register a new producer
Usage: cleos system regproducer [OPTIONS] account producer_key [url] location

Positionals:
  account TEXT                The account to register as a producer (required)
  producer_key TEXT           The producer's public key (required)
  url TEXT                    url where info about producer can be found
  location INT=0              time zone from -11 to 12 (required)
```
the command is that ,and you should  exec 
```
sudo docker exec nodeosd cleos system regproducer bp1 EOS7japcYUEQprwmt4W3RLSq1Fp6PueSwMQFt8FFHuDpDouZgSeZ9 www.xxxx.com  2
```

**Comment by snowlybetter** [comment]
> In docker enviroment use boscore/bos:latest image.
> I have aleady set contracts and use use `system newaccount` create account
> 
> ```
> sudo docker exec nodeosd cleos system newaccount eosio bp1 EOS7japcYUEQprwmt4W3RLSq1Fp6PueSwMQFt8FFHuDpDouZgSeZ9 EOS7japcYUEQprwmt4W3RLSq1Fp6PueSwMQFt8FFHuDpDouZgSeZ9 --stake-net "1000000.0000 BOS" --    stake-cpu "1000000.0000 BOS" --buy-ram-kbytes "128000 KiB"
> ```
> but when I registered the new account as a producer，encountered a problem that command need a location, then I set location:
> 
> ```
> sudo docker exec nodeosd cleos system regproducer bp1 EOS7japcYUEQprwmt4W3RLSq1Fp6PueSwMQFt8FFHuDpDouZgSeZ9 2
> ```
> stilling get the error, have tried 0 / 1 / '0' in posiiton of location in command:
> 
> ```
> ERROR: RequiredError: location
> Register a new producer
> Usage: cleos system regproducer [OPTIONS] account producer_key [url] location
> 
> Positionals:
>   account TEXT                The account to register as a producer (required)
>   producer_key TEXT           The producer's public key (required)
>   url TEXT                    url where info about producer can be found
>   location INT=0              time zone from -11 to 12 (required)
> ```
> Anyone knows how to solve this, please tell me.
