### ISSUE TITLE
低保功能，通过多签修改低保的门槛功能问题

### ISSUE THREAD

**Issue by snowlybetter** [boscore/bos#9]
目前系统默认的每个账户的低保是：cpu:20ms、net:10kib；如果想对低保账户进行设置的话，需要多签setminguar操作，但是这个action最大允许设置cpu:100us、net:100byte，步长是10；这样的话就会导致咱们无法调大低保资源的参数，只能缩小，并且很小。

**Comment by vlbos** [comment]
fixed this issue in bos.contracts repo   https://github.com/boscore/bos.contracts/commit/d441020cef65aec681a6db3d30f15de4ecf78425#diff-8075b0acd416e83ad39e00f334ccd199

**Comment by Thaipanda** [comment]
this has been fixed, please try v2.0.1
